version: '3'
services:
  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend 