[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"  // Explícito para Railway

[deploy]
startCommand = ""  // Fuerza uso de CMD del Dockerfile

[env]
PORT = "3000"  // Fallback, aunque Docker lo maneja 